-- 20260731d — ПОДГОТОВЛЕНО, НЕ ПРИМЕНЕНО. Ждёт слова владельца.
--
-- НАХОДКА (замер 31.07, случай Balas Derrick). На карточке ребёнка поля
-- «AGE GROUP» и «MILK (OZ)» показывают «—» при заполненной дате рождения. Причина
-- НЕ в данных: представление считает всё правильно —
--
--   select age_months, cacfp_food_group, milk_type, milk_oz
--   from menumaker.v_child_age_profile
--   where id = '3555bb51-cce1-4bf2-a4b1-86d388106905';
--   → 88 · 6_12y · 1pct · 8
--
-- Причина в ПРАВАХ: у представления НЕТ гранта роли `authenticated` —
--
--   select grantee, privilege_type from information_schema.role_table_grants
--   where table_schema='menumaker' and table_name='v_child_age_profile';
--   → только postgres и service_role
--
-- Приложение ходит под `authenticated`, получает отказ прав, а код на
-- ChildSettingsPage:234 этот отказ ГЛОТАЛ (`const { data: vw } = …` без error).
-- Отказ прав стал неотличим от пустоты — тот самый класс, что стоит в канонах.
-- Код уже исправлен (ошибка связана и печатается словами); грант закрывает причину.
--
-- ⚠️ ЭТО КАСАЕТСЯ ВСЕХ ДЕТЕЙ, а не одного: поля пусты у каждого, кто открывает
-- вкладку CACFP. Питание и клейм НЕ затронуты — они читают roster.age_group_food и
-- собственную функцию, а не это представление.
--
-- БЕЗОПАСНОСТЬ: представление выводит возраст/молоко из roster, который директор и
-- так читает; строковой политики у представления нет (relrowsecurity=false), поэтому
-- грант даёт ровно то же, что уже доступно через roster. Права на запись НЕ даются.
--
-- READ-BACK: открыть карточку любого ребёнка с датой рождения → «AGE GROUP» и
-- «MILK (OZ)» заполнены; предупреждение под ними исчезло.

grant select on menumaker.v_child_age_profile to authenticated;
