-- 20260806v — v_meal_grid перестаёт читаться без логина (дорога 1, 06.08)
--
-- ЗАМЕР: у представления есть grant anon:SELECT и НЕТ security_invoker, то есть
-- оно читает базовые таблицы правами владельца, в обход RLS. anon-ключ лежит в
-- клиентском бандле — значит детские строки всей организации читались без логина.
--
-- НИ ОДНА живая поверхность не читает представление под anon: MealCountPage и
-- SafePassTeacherPage работают под authenticated (маршрут внутри ProtectedRoute),
-- а родительский экран, /t/<token> и водитель ходят через SECURITY DEFINER RPC.
-- Поэтому снятие гранта — правка без потребителя.
--
-- security_invoker НЕ ТРОГАЕМ НАРОЧНО: обход RLS здесь — НЕСУЩАЯ конструкция
-- (у ростера есть door_read_scope и teacher_scoped_read; сетка счёта у повара и
-- учителя опустела бы). Полное лечение — заход «ДЕТСКАЯ СТЕНА»: центровая стена
-- ростера + invoker + токен-RPC meal_grid_for_room(p_token, p_classroom).
revoke select on menumaker.v_meal_grid from anon;
